### PR TITLE
Merge digikar's changes

### PR DESCRIPTION
**Pull request by phoe**
@digikar99 Mind if I merge your wordnet changes into my branch? They seem pretty good, especially considering the README that I mostly just copied over from Mark Nahabedian's original release.

### CODE REVIEW

**Comment by phoe** [comment]
@digikar99 oops, mentioned a wrong name. Sorry!

**Comment by MarkNahabedian** [comment]
Near as I can tell there are no incompatible changes.

You should be happy to know that MIT has released this code (what I've written of it) under it's public license.  I don't know if the GitHub repository mentions that.

On Apr 27, 2020 5:21 PM, phoe <notifications@github.com> wrote:

@digikar99<https://github.com/digikar99> Mind if I merge your wordnet changes into my branch? They seem pretty good, especially considering the README that I mostly just copied over from Mark Nahabedian's original release.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/phoe/wordnet/pull/2

Commit Summary

  *   added documentation for cached-index-lookup
  *   changed argument-order of synsets-containing-words and renamed to word/s
  *   updated usage of synsets-containing-word/s in get-synonyms and get-antonyms
  *   made part-of-speech optional argument for synsets-containing-words and get-synonyms
  *   added simpler documentation
  *   minor corrections

File Changes

  *   M README.md<https://github.com/phoe/wordnet/pull/2/files#diff-04c6e90faac2675aa89e2176d2eec7d8> (197)
  *   M examples.lisp<https://github.com/phoe/wordnet/pull/2/files#diff-f04ae732a02653258e21bfde99de40ea> (26)
  *   M packages.lisp<https://github.com/phoe/wordnet/pull/2/files#diff-db9aa6c5b0320888a4ae02b3b812ed96> (2)
  *   M representation.lisp<https://github.com/phoe/wordnet/pull/2/files#diff-1a664f7484efcc539cb6413daa9c4f8a> (22)

Patch Links:

  *   https://github.com/phoe/wordnet/pull/2.patch
  *   https://github.com/phoe/wordnet/pull/2.diff

-

**Comment by phoe** [comment]
> You should be happy to know that MIT has released this code (what I've written of it) under it's public license.  I don't know if the GitHub repository mentions that.

Yes, I remember that fight. It took us a long while to get the https://github.com/phoe/wordnet/blob/master/LICENSE file. :smile:

**Comment by digikar99** [comment]
> @digikar99 Mind if I merge your wordnet changes into my branch?

Oh yes, sure, no issues with it. You can go ahead with the merge.

**Pull request merged**
